export const FACETS_CONFIGS = {
  agent: [
    "agentActiveDate",
    "agentActivePlaceId",
    "agentEndDate",
    "agentEndPlaceId",
    "agentGenderId",
    "agentHasDigitalImage",
    "agentMemberOfId",
    "agentNationalityId",
    "agentOccupationId",
    "agentProfessionalActivityId",
    "agentRecordType",
    "agentStartDate",
    "agentStartPlaceId",
    "agentTypeId",
  ],
  concept: [
    "conceptInfluencedByAgentId",
    "conceptInfluencedByConceptId",
    "conceptInfluencedByEventId",
    "conceptInfluencedByPlaceId",
    "conceptPartOfId",
    "conceptRecordType",
    "conceptTypeId",
  ],
  event: [
    "eventAgentId",
    "eventEndDate",
    "eventPlaceId",
    "eventRecordType",
    "eventStartDate",
    "eventTypeId",
  ],
  item: [
    "itemEncounteredAgentId",
    "itemEncounteredDate",
    "itemEncounteredPlaceId",
    "itemHasDigitalImage",
    "itemIsOnline",
    "itemMaterialId",
    "itemProductionAgentId",
    "itemProductionDate",
    "itemProductionPlaceId",
    "itemRecordType",
    "itemTypeId",
    "itemResponsibleCollections", // semantic
    "itemResponsibleUnits", // semantic
  ],
  place: [
    "placePartOfId",
    "placeTypeId",
  ],
  set: [
    "setAboutAgentId",
    "setAboutConceptId",
    "setAboutEventId",
    "setAboutItemId",
    "setAboutPlaceId",
    "setAboutSetId",
    "setAboutWorkId",
    "setCreationAgentId",
    "setCreationDate",
    "setCreationPlaceId",
    "setCurationAgentId",
    "setHasDigitalImage",
    "setIsOnline",
    "setPublicationAgentId",
    "setPublicationDate",
    "setPublicationPlaceId",
    "setResponsibleCollections", // semantic
    "setResponsibleUnits", // semantic
    "setTypeId",
  ],
  work: [
    "workAboutAgentId",
    "workAboutConceptId",
    "workAboutEventId",
    "workAboutItemId",
    "workAboutPlaceId",
    "workAboutSetId",
    "workAboutWorkId",
    "workCreationAgentId",
    "workCreationDate",
    "workCreationPlaceId",
    "workHasDigitalImage",
    "workIsOnline",
    "workLanguageId",
    "workPublicationAgentId",
    "workPublicationDate",
    "workPublicationPlaceId",
    "workRecordType",
    "workTypeId",
  ],
};
